# build stage
FROM node:24 AS build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm ci
COPY . /app/
RUN npm run build

# production stage: the static files are copied into the nginx volume
FROM alpine:3.22 AS production-stage
RUN mkdir -p /vue
COPY --from=build-stage /app/dist /vue

CMD ["tail", "-f", "/dev/null"]
