/* eslint-disable */
// Generated by 'npm run types' from src/schema/annotation.schema.json, do not edit.

/**
 * Everything the report shows of one resource of an annotation.
 */
export interface AnnotationResource {
  resource: string;
  collection?: Collection | null;
  identifier?: string | null;
  url?: string | null;
  patternMatch?: boolean | null;
  providers?: Provider[];
  ontology?: OntologyTerm | null;
  chebi?: ChebiInfo | null;
  uniprot?: UniprotInfo | null;
  warnings?: string[];
  errors?: string[];
}
/**
 * The collection of the identifiers.org registry a resource belongs to.
 */
export interface Collection {
  prefix: string;
  name?: string | null;
  homepage?: string | null;
}
/**
 * A provider which resolves the identifier of a resource.
 */
export interface Provider {
  name: string;
  url: string;
  official: boolean;
}
/**
 * The term of a resource in the Ontology Lookup Service.
 */
export interface OntologyTerm {
  ontology?: string | null;
  label?: string | null;
  iri?: string | null;
  olsUrl?: string | null;
  description?: string | null;
  synonyms?: string[];
  xrefs?: CrossReference[];
}
/**
 * A cross reference of an ontology term, a link where OLS gives an url.
 */
export interface CrossReference {
  label: string;
  url?: string | null;
}
/**
 * The chemical information of a ChEBI compound.
 */
export interface ChebiInfo {
  formula?: string | null;
  charge?: number | null;
  mass?: string | null;
  structure?: boolean;
}
/**
 * The information of a UniProt protein.
 */
export interface UniprotInfo {
  entry?: string | null;
  name?: string | null;
  organism?: string | null;
  genes?: string[];
  length?: number | null;
  function?: string | null;
}
