/* eslint-disable */
// Generated by 'npm run types' from src/schema/report.schema.json, do not edit.

export type Uid = string;
export type Location = string;
export type Format = string;
export type Master = boolean;
export type Entries = ManifestEntry[];
export type Pk = string;
export type Sbmltype = "SBMLDocument";
export type Id = string | null;
export type Metaid = string | null;
export type Name = string | null;
export type Sbo = string | null;
export type Notes = string | null;
export type Qualifier = string;
export type Resources = string[];
export type Cvterms = CVTerm[];
export type Givenname = string | null;
export type Familyname = string | null;
export type Organization = string | null;
export type Email = string | null;
export type Creators = Creator[];
export type Createddate = string | null;
export type Modifieddates = string[];
export type Xml = string | null;
export type Submodelref = string;
export type Portref = string | null;
export type Idref = string | null;
export type Unitref = string | null;
export type Metaidref = string | null;
export type Submodelref1 = string;
export type Replacedelements = ReplacedElement[];
export type Pk1 = string;
export type Sbmltype1 = "Uncertainty";
export type Id1 = string | null;
export type Metaid1 = string | null;
export type Name1 = string | null;
export type Sbo1 = string | null;
export type Notes1 = string | null;
export type Cvterms1 = CVTerm[];
export type Xml1 = string | null;
export type Uncertainties1 = Uncertainty[];
export type Var = string | null;
export type Value = number | null;
export type Units = string | null;
export type Type = string | null;
export type Definitionurl = string | null;
export type Latex = string;
export type Formula = string;
export type Uncertparameters = UncertParameter[];
export type Uncertainties = Uncertainty[];
export type Level = number;
export type Version = number;
export type Prefix = string;
export type Version1 = number;
export type Packages = Package[];
export type Pk2 = string;
export type Sbmltype2 = "Model";
export type Id2 = string | null;
export type Metaid2 = string | null;
export type Name2 = string | null;
export type Sbo2 = string | null;
export type Notes2 = string | null;
export type Cvterms2 = CVTerm[];
export type Xml2 = string | null;
export type Uncertainties2 = Uncertainty[];
export type Kind = "model" | "modelDefinition";
export type Substanceunits = string | null;
export type Substanceunitslatex = string | null;
export type Timeunits = string | null;
export type Timeunitslatex = string | null;
export type Volumeunits = string | null;
export type Volumeunitslatex = string | null;
export type Areaunits = string | null;
export type Areaunitslatex = string | null;
export type Lengthunits = string | null;
export type Lengthunitslatex = string | null;
export type Extentunits = string | null;
export type Extentunitslatex = string | null;
export type Sid = string;
export type Value1 = number | null;
export type Units1 = string | null;
export type Pk3 = string;
export type Sbmltype3 = "FunctionDefinition";
export type Id3 = string | null;
export type Metaid3 = string | null;
export type Name3 = string | null;
export type Sbo3 = string | null;
export type Notes3 = string | null;
export type Cvterms3 = CVTerm[];
export type Xml3 = string | null;
export type Uncertainties3 = Uncertainty[];
export type Listoffunctiondefinitions = FunctionDefinition[];
export type Pk4 = string;
export type Sbmltype4 = "UnitDefinition";
export type Id4 = string | null;
export type Metaid4 = string | null;
export type Name4 = string | null;
export type Sbo4 = string | null;
export type Notes4 = string | null;
export type Cvterms4 = CVTerm[];
export type Xml4 = string | null;
export type Uncertainties4 = Uncertainty[];
export type Unitslatex = string | null;
export type Listofunitdefinitions = UnitDefinition[];
export type Pk5 = string;
export type Sbmltype5 = "Compartment";
export type Id5 = string | null;
export type Metaid5 = string | null;
export type Name5 = string | null;
export type Sbo5 = string | null;
export type Notes5 = string | null;
export type Cvterms5 = CVTerm[];
export type Xml5 = string | null;
export type Uncertainties5 = Uncertainty[];
export type Spatialdimensions = number | null;
export type Size = number | null;
export type Constant = boolean | null;
export type Units2 = string | null;
export type Unitslatex1 = string | null;
export type Derivedunits = string | null;
export type Listofcompartments = Compartment[];
export type Pk6 = string;
export type Sbmltype6 = "Species";
export type Id6 = string | null;
export type Metaid6 = string | null;
export type Name6 = string | null;
export type Sbo6 = string | null;
export type Notes6 = string | null;
export type Cvterms6 = CVTerm[];
export type Xml6 = string | null;
export type Uncertainties6 = Uncertainty[];
export type Compartment1 = string;
export type Initialamount = number | null;
export type Initialconcentration = number | null;
export type Substanceunits1 = string | null;
export type Hasonlysubstanceunits = boolean | null;
export type Boundarycondition = boolean | null;
export type Constant1 = boolean | null;
export type Unitslatex2 = string | null;
export type Derivedunits1 = string | null;
export type Chemicalformula = string | null;
export type Charge = number | null;
export type Listofspecies = Species[];
export type Pk7 = string;
export type Sbmltype7 = "Parameter";
export type Id7 = string | null;
export type Metaid7 = string | null;
export type Name7 = string | null;
export type Sbo7 = string | null;
export type Notes7 = string | null;
export type Cvterms7 = CVTerm[];
export type Xml7 = string | null;
export type Uncertainties7 = Uncertainty[];
export type Value2 = number | null;
export type Constant2 = boolean | null;
export type Units3 = string | null;
export type Unitslatex3 = string | null;
export type Derivedunits2 = string | null;
export type Listofparameters = Parameter[];
export type Pk8 = string;
export type Sbmltype8 = "InitialAssignment";
export type Id8 = string | null;
export type Metaid8 = string | null;
export type Name8 = string | null;
export type Sbo8 = string | null;
export type Notes8 = string | null;
export type Cvterms8 = CVTerm[];
export type Xml8 = string | null;
export type Uncertainties8 = Uncertainty[];
export type Symbol = string;
export type Derivedunits3 = string | null;
export type Listofinitialassignments = InitialAssignment[];
export type Pk9 = string;
export type Sbmltype9 = "AssignmentRule";
export type Id9 = string | null;
export type Metaid9 = string | null;
export type Name9 = string | null;
export type Sbo9 = string | null;
export type Notes9 = string | null;
export type Cvterms9 = CVTerm[];
export type Xml9 = string | null;
export type Uncertainties9 = Uncertainty[];
export type Variable = string;
export type Derivedunits4 = string | null;
export type Pk10 = string;
export type Sbmltype10 = "RateRule";
export type Id10 = string | null;
export type Metaid10 = string | null;
export type Name10 = string | null;
export type Sbo10 = string | null;
export type Notes10 = string | null;
export type Cvterms10 = CVTerm[];
export type Xml10 = string | null;
export type Uncertainties10 = Uncertainty[];
export type Variable1 = string;
export type Derivedunits5 = string | null;
export type Pk11 = string;
export type Sbmltype11 = "AlgebraicRule";
export type Id11 = string | null;
export type Metaid11 = string | null;
export type Name11 = string | null;
export type Sbo11 = string | null;
export type Notes11 = string | null;
export type Cvterms11 = CVTerm[];
export type Xml11 = string | null;
export type Uncertainties11 = Uncertainty[];
export type Derivedunits6 = string | null;
export type Listofrules = (AssignmentRule | RateRule | AlgebraicRule)[];
export type Pk12 = string;
export type Sbmltype12 = "Constraint";
export type Id12 = string | null;
export type Metaid12 = string | null;
export type Name12 = string | null;
export type Sbo12 = string | null;
export type Notes12 = string | null;
export type Cvterms12 = CVTerm[];
export type Xml12 = string | null;
export type Uncertainties12 = Uncertainty[];
export type Message = string | null;
export type Listofconstraints = Constraint[];
export type Pk13 = string;
export type Sbmltype13 = "Reaction";
export type Id13 = string | null;
export type Metaid13 = string | null;
export type Name13 = string | null;
export type Sbo13 = string | null;
export type Notes13 = string | null;
export type Cvterms13 = CVTerm[];
export type Xml13 = string | null;
export type Uncertainties13 = Uncertainty[];
export type Reversible = boolean | null;
export type Fast = boolean | null;
export type Compartment2 = string | null;
export type Pk14 = string;
export type Sbmltype14 = "SpeciesReference";
export type Id14 = string | null;
export type Metaid14 = string | null;
export type Name14 = string | null;
export type Sbo14 = string | null;
export type Notes14 = string | null;
export type Cvterms14 = CVTerm[];
export type Xml14 = string | null;
export type Uncertainties14 = Uncertainty[];
export type Species1 = string;
export type Stoichiometry = number | null;
export type Constant3 = boolean | null;
export type Listofreactants = SpeciesReference[];
export type Listofproducts = SpeciesReference[];
export type Pk15 = string;
export type Sbmltype15 = "ModifierSpeciesReference";
export type Id15 = string | null;
export type Metaid15 = string | null;
export type Name15 = string | null;
export type Sbo15 = string | null;
export type Notes15 = string | null;
export type Cvterms15 = CVTerm[];
export type Xml15 = string | null;
export type Uncertainties15 = Uncertainty[];
export type Species2 = string;
export type Listofmodifiers = ModifierSpeciesReference[];
export type Pk16 = string;
export type Sbmltype16 = "KineticLaw";
export type Id16 = string | null;
export type Metaid16 = string | null;
export type Name16 = string | null;
export type Sbo16 = string | null;
export type Notes16 = string | null;
export type Cvterms16 = CVTerm[];
export type Xml16 = string | null;
export type Uncertainties16 = Uncertainty[];
export type Derivedunits7 = string | null;
export type Pk17 = string;
export type Sbmltype17 = "LocalParameter";
export type Id17 = string | null;
export type Metaid17 = string | null;
export type Name17 = string | null;
export type Sbo17 = string | null;
export type Notes17 = string | null;
export type Cvterms17 = CVTerm[];
export type Xml17 = string | null;
export type Uncertainties17 = Uncertainty[];
export type Value3 = number | null;
export type Units4 = string | null;
export type Unitslatex4 = string | null;
export type Derivedunits8 = string | null;
export type Listoflocalparameters = LocalParameter[];
export type Equation = string;
export type Lowerfluxbound = string | null;
export type Upperfluxbound = string | null;
export type Geneproductassociation = string | null;
export type Geneproducts = string[];
export type Listofreactions = Reaction[];
export type Pk18 = string;
export type Sbmltype18 = "Event";
export type Id18 = string | null;
export type Metaid18 = string | null;
export type Name18 = string | null;
export type Sbo18 = string | null;
export type Notes18 = string | null;
export type Cvterms18 = CVTerm[];
export type Xml18 = string | null;
export type Uncertainties18 = Uncertainty[];
export type Usevaluesfromtriggertime = boolean | null;
export type Initialvalue = boolean | null;
export type Persistent = boolean | null;
export type Pk19 = string;
export type Sbmltype19 = "EventAssignment";
export type Id19 = string | null;
export type Metaid19 = string | null;
export type Name19 = string | null;
export type Sbo19 = string | null;
export type Notes19 = string | null;
export type Cvterms19 = CVTerm[];
export type Xml19 = string | null;
export type Uncertainties19 = Uncertainty[];
export type Variable2 = string;
export type Listofeventassignments = EventAssignment[];
export type Listofevents = Event[];
export type Pk20 = string;
export type Sbmltype20 = "Submodel";
export type Id20 = string | null;
export type Metaid20 = string | null;
export type Name20 = string | null;
export type Sbo20 = string | null;
export type Notes20 = string | null;
export type Cvterms20 = CVTerm[];
export type Xml20 = string | null;
export type Uncertainties20 = Uncertainty[];
export type Modelref = string;
export type Timeconversionfactor = string | null;
export type Extentconversionfactor = string | null;
export type Listofdeletions = SBaseRef[];
export type Listofsubmodels = Submodel[];
export type Pk21 = string;
export type Sbmltype21 = "Port";
export type Id21 = string | null;
export type Metaid21 = string | null;
export type Name21 = string | null;
export type Sbo21 = string | null;
export type Notes21 = string | null;
export type Cvterms21 = CVTerm[];
export type Xml21 = string | null;
export type Uncertainties21 = Uncertainty[];
export type Portref1 = string | null;
export type Idref1 = string | null;
export type Unitref1 = string | null;
export type Metaidref1 = string | null;
export type Listofports = Port[];
export type Pk22 = string;
export type Sbmltype22 = "GeneProduct";
export type Id22 = string | null;
export type Metaid22 = string | null;
export type Name22 = string | null;
export type Sbo22 = string | null;
export type Notes22 = string | null;
export type Cvterms22 = CVTerm[];
export type Xml22 = string | null;
export type Uncertainties22 = Uncertainty[];
export type Label = string | null;
export type Associatedspecies = string | null;
export type Listofgeneproducts = GeneProduct[];
export type Pk23 = string;
export type Sbmltype23 = "Objective";
export type Id23 = string | null;
export type Metaid23 = string | null;
export type Name23 = string | null;
export type Sbo23 = string | null;
export type Notes23 = string | null;
export type Cvterms23 = CVTerm[];
export type Xml23 = string | null;
export type Uncertainties23 = Uncertainty[];
export type Type1 = string | null;
export type Reaction1 = string;
export type Coefficient = number | null;
export type Listoffluxobjectives = FluxObjective[];
export type Listofobjectives = Objective[];
export type Models = Model[];
export type Pk24 = string;
export type Sbmltype24 = "ExternalModelDefinition";
export type Id24 = string | null;
export type Metaid24 = string | null;
export type Name24 = string | null;
export type Sbo24 = string | null;
export type Notes24 = string | null;
export type Cvterms24 = CVTerm[];
export type Xml24 = string | null;
export type Uncertainties24 = Uncertainty[];
export type Source = string;
export type Modelref1 = string | null;
export type Externalmodeldefinitions = ExternalModelDefinition[];
export type Pk25 = string;
export type Sbmltype25 = string;
export type Id25 = string | null;
export type Name25 = string | null;
export type Model1 = string | null;
export type Source1 = string;
export type Target = string;
/**
 * The kinds of references between objects.
 */
export type EdgeKind =
  | "compartment"
  | "reactant"
  | "product"
  | "modifier"
  | "variable"
  | "symbol"
  | "units"
  | "conversionFactor"
  | "fluxBound"
  | "geneProduct"
  | "associatedSpecies"
  | "fluxObjective"
  | "modelRef"
  | "port"
  | "replacedBy"
  | "replacedElement"
  | "math";
export type Edges = Edge[];
export type Jsonreporttime = string;

/**
 * The response of the api: the manifest and one report per SBML entry.
 */
export interface ReportResponse {
  uid: Uid;
  manifest: Manifest;
  reports: Reports;
}
/**
 * The manifest of a COMBINE archive.
 */
export interface Manifest {
  entries?: Entries;
}
/**
 * An entry of the manifest of a COMBINE archive.
 */
export interface ManifestEntry {
  location: Location;
  format: Format;
  master?: Master;
}
export interface Reports {
  [k: string]: ReportEntry;
}
/**
 * The report of one SBML entry of an archive.
 */
export interface ReportEntry {
  report: Report;
  debug: Debug;
}
/**
 * The report of one SBML document.
 */
export interface Report {
  document: SBMLDocument;
  models?: Models;
  externalModelDefinitions?: Externalmodeldefinitions;
  linkGraph?: LinkGraph;
}
/**
 * The document: level, version and the packages it uses.
 */
export interface SBMLDocument {
  pk: Pk;
  sbmlType?: Sbmltype;
  id?: Id;
  metaId?: Metaid;
  name?: Name;
  sbo?: Sbo;
  notes?: Notes;
  cvterms?: Cvterms;
  history?: ModelHistory | null;
  xml?: Xml;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties;
  level: Level;
  version: Version;
  packages?: Packages;
}
/**
 * An annotation: a qualifier (BQB or BQM of pymetadata) with its resources.
 */
export interface CVTerm {
  qualifier: Qualifier;
  resources: Resources;
}
/**
 * The history of an element: creators and dates.
 */
export interface ModelHistory {
  creators?: Creators;
  createdDate?: Createddate;
  modifiedDates?: Modifieddates;
}
/**
 * A creator of the model history.
 */
export interface Creator {
  givenName?: Givenname;
  familyName?: Familyname;
  organization?: Organization;
  email?: Email;
}
/**
 * The comp extension of an element.
 */
export interface CompSBase {
  replacedBy?: ReplacedBy | null;
  replacedElements?: Replacedelements;
}
/**
 * The element of a submodel which replaces this element.
 */
export interface ReplacedBy {
  submodelRef: Submodelref;
  sbaseRef: SBaseRef;
}
/**
 * A comp reference to an element by port, id, unit or metaId.
 */
export interface SBaseRef {
  portRef?: Portref;
  idRef?: Idref;
  unitRef?: Unitref;
  metaIdRef?: Metaidref;
}
/**
 * An element of a submodel which this element replaces.
 */
export interface ReplacedElement {
  submodelRef: Submodelref1;
  sbaseRef: SBaseRef;
}
/**
 * A distrib uncertainty of an element.
 */
export interface Uncertainty {
  pk: Pk1;
  sbmlType?: Sbmltype1;
  id?: Id1;
  metaId?: Metaid1;
  name?: Name1;
  sbo?: Sbo1;
  notes?: Notes1;
  cvterms?: Cvterms1;
  history?: ModelHistory | null;
  xml?: Xml1;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties1;
  uncertParameters?: Uncertparameters;
}
/**
 * A parameter of a distrib uncertainty.
 */
export interface UncertParameter {
  var?: Var;
  value?: Value;
  units?: Units;
  type?: Type;
  definitionUrl?: Definitionurl;
  math?: Math | null;
}
/**
 * The math of an element as latex and as L3 formula string.
 */
export interface Math {
  latex: Latex;
  formula: Formula;
}
/**
 * An SBML package used by the document.
 */
export interface Package {
  prefix: Prefix;
  version: Version1;
}
/**
 * A model or comp model definition with the lists of its elements.
 */
export interface Model {
  pk: Pk2;
  sbmlType?: Sbmltype2;
  id?: Id2;
  metaId?: Metaid2;
  name?: Name2;
  sbo?: Sbo2;
  notes?: Notes2;
  cvterms?: Cvterms2;
  history?: ModelHistory | null;
  xml?: Xml2;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties2;
  kind?: Kind;
  substanceUnits?: Substanceunits;
  substanceUnitsLatex?: Substanceunitslatex;
  timeUnits?: Timeunits;
  timeUnitsLatex?: Timeunitslatex;
  volumeUnits?: Volumeunits;
  volumeUnitsLatex?: Volumeunitslatex;
  areaUnits?: Areaunits;
  areaUnitsLatex?: Areaunitslatex;
  lengthUnits?: Lengthunits;
  lengthUnitsLatex?: Lengthunitslatex;
  extentUnits?: Extentunits;
  extentUnitsLatex?: Extentunitslatex;
  conversionFactor?: ConversionFactor | null;
  listOfFunctionDefinitions?: Listoffunctiondefinitions;
  listOfUnitDefinitions?: Listofunitdefinitions;
  listOfCompartments?: Listofcompartments;
  listOfSpecies?: Listofspecies;
  listOfParameters?: Listofparameters;
  listOfInitialAssignments?: Listofinitialassignments;
  listOfRules?: Listofrules;
  listOfConstraints?: Listofconstraints;
  listOfReactions?: Listofreactions;
  listOfEvents?: Listofevents;
  listOfSubmodels?: Listofsubmodels;
  listOfPorts?: Listofports;
  listOfGeneProducts?: Listofgeneproducts;
  listOfObjectives?: Listofobjectives;
}
/**
 * The conversion factor parameter of a model or species.
 */
export interface ConversionFactor {
  sid: Sid;
  value?: Value1;
  units?: Units1;
}
/**
 * A function definition with its lambda.
 */
export interface FunctionDefinition {
  pk: Pk3;
  sbmlType?: Sbmltype3;
  id?: Id3;
  metaId?: Metaid3;
  name?: Name3;
  sbo?: Sbo3;
  notes?: Notes3;
  cvterms?: Cvterms3;
  history?: ModelHistory | null;
  xml?: Xml3;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties3;
  math?: Math | null;
}
/**
 * A unit definition with its rendered units.
 */
export interface UnitDefinition {
  pk: Pk4;
  sbmlType?: Sbmltype4;
  id?: Id4;
  metaId?: Metaid4;
  name?: Name4;
  sbo?: Sbo4;
  notes?: Notes4;
  cvterms?: Cvterms4;
  history?: ModelHistory | null;
  xml?: Xml4;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties4;
  unitsLatex?: Unitslatex;
}
/**
 * A compartment.
 */
export interface Compartment {
  pk: Pk5;
  sbmlType?: Sbmltype5;
  id?: Id5;
  metaId?: Metaid5;
  name?: Name5;
  sbo?: Sbo5;
  notes?: Notes5;
  cvterms?: Cvterms5;
  history?: ModelHistory | null;
  xml?: Xml5;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties5;
  spatialDimensions?: Spatialdimensions;
  size?: Size;
  constant?: Constant;
  units?: Units2;
  unitsLatex?: Unitslatex1;
  derivedUnits?: Derivedunits;
}
/**
 * A species.
 */
export interface Species {
  pk: Pk6;
  sbmlType?: Sbmltype6;
  id?: Id6;
  metaId?: Metaid6;
  name?: Name6;
  sbo?: Sbo6;
  notes?: Notes6;
  cvterms?: Cvterms6;
  history?: ModelHistory | null;
  xml?: Xml6;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties6;
  compartment: Compartment1;
  initialAmount?: Initialamount;
  initialConcentration?: Initialconcentration;
  substanceUnits?: Substanceunits1;
  hasOnlySubstanceUnits?: Hasonlysubstanceunits;
  boundaryCondition?: Boundarycondition;
  constant?: Constant1;
  unitsLatex?: Unitslatex2;
  derivedUnits?: Derivedunits1;
  conversionFactor?: ConversionFactor | null;
  fbc?: SpeciesFbc | null;
}
/**
 * The fbc extension of a species.
 */
export interface SpeciesFbc {
  chemicalFormula?: Chemicalformula;
  charge?: Charge;
}
/**
 * A global parameter.
 */
export interface Parameter {
  pk: Pk7;
  sbmlType?: Sbmltype7;
  id?: Id7;
  metaId?: Metaid7;
  name?: Name7;
  sbo?: Sbo7;
  notes?: Notes7;
  cvterms?: Cvterms7;
  history?: ModelHistory | null;
  xml?: Xml7;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties7;
  value?: Value2;
  constant?: Constant2;
  units?: Units3;
  unitsLatex?: Unitslatex3;
  derivedUnits?: Derivedunits2;
}
/**
 * An initial assignment of a symbol.
 */
export interface InitialAssignment {
  pk: Pk8;
  sbmlType?: Sbmltype8;
  id?: Id8;
  metaId?: Metaid8;
  name?: Name8;
  sbo?: Sbo8;
  notes?: Notes8;
  cvterms?: Cvterms8;
  history?: ModelHistory | null;
  xml?: Xml8;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties8;
  symbol: Symbol;
  math?: Math | null;
  derivedUnits?: Derivedunits3;
}
/**
 * An assignment rule of a variable.
 */
export interface AssignmentRule {
  pk: Pk9;
  sbmlType?: Sbmltype9;
  id?: Id9;
  metaId?: Metaid9;
  name?: Name9;
  sbo?: Sbo9;
  notes?: Notes9;
  cvterms?: Cvterms9;
  history?: ModelHistory | null;
  xml?: Xml9;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties9;
  variable: Variable;
  math?: Math | null;
  derivedUnits?: Derivedunits4;
}
/**
 * A rate rule of a variable.
 */
export interface RateRule {
  pk: Pk10;
  sbmlType?: Sbmltype10;
  id?: Id10;
  metaId?: Metaid10;
  name?: Name10;
  sbo?: Sbo10;
  notes?: Notes10;
  cvterms?: Cvterms10;
  history?: ModelHistory | null;
  xml?: Xml10;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties10;
  variable: Variable1;
  math?: Math | null;
  derivedUnits?: Derivedunits5;
}
/**
 * An algebraic rule.
 */
export interface AlgebraicRule {
  pk: Pk11;
  sbmlType?: Sbmltype11;
  id?: Id11;
  metaId?: Metaid11;
  name?: Name11;
  sbo?: Sbo11;
  notes?: Notes11;
  cvterms?: Cvterms11;
  history?: ModelHistory | null;
  xml?: Xml11;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties11;
  math?: Math | null;
  derivedUnits?: Derivedunits6;
}
/**
 * A constraint with its message.
 */
export interface Constraint {
  pk: Pk12;
  sbmlType?: Sbmltype12;
  id?: Id12;
  metaId?: Metaid12;
  name?: Name12;
  sbo?: Sbo12;
  notes?: Notes12;
  cvterms?: Cvterms12;
  history?: ModelHistory | null;
  xml?: Xml12;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties12;
  math?: Math | null;
  message?: Message;
}
/**
 * A reaction with its participants and kinetic law.
 */
export interface Reaction {
  pk: Pk13;
  sbmlType?: Sbmltype13;
  id?: Id13;
  metaId?: Metaid13;
  name?: Name13;
  sbo?: Sbo13;
  notes?: Notes13;
  cvterms?: Cvterms13;
  history?: ModelHistory | null;
  xml?: Xml13;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties13;
  reversible?: Reversible;
  fast?: Fast;
  compartment?: Compartment2;
  listOfReactants?: Listofreactants;
  listOfProducts?: Listofproducts;
  listOfModifiers?: Listofmodifiers;
  kineticLaw?: KineticLaw | null;
  equation: Equation;
  fbc?: ReactionFbc | null;
}
/**
 * A reactant or product of a reaction.
 */
export interface SpeciesReference {
  pk: Pk14;
  sbmlType?: Sbmltype14;
  id?: Id14;
  metaId?: Metaid14;
  name?: Name14;
  sbo?: Sbo14;
  notes?: Notes14;
  cvterms?: Cvterms14;
  history?: ModelHistory | null;
  xml?: Xml14;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties14;
  species: Species1;
  stoichiometry?: Stoichiometry;
  constant?: Constant3;
}
/**
 * A modifier of a reaction.
 */
export interface ModifierSpeciesReference {
  pk: Pk15;
  sbmlType?: Sbmltype15;
  id?: Id15;
  metaId?: Metaid15;
  name?: Name15;
  sbo?: Sbo15;
  notes?: Notes15;
  cvterms?: Cvterms15;
  history?: ModelHistory | null;
  xml?: Xml15;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties15;
  species: Species2;
}
/**
 * The kinetic law of a reaction.
 */
export interface KineticLaw {
  pk: Pk16;
  sbmlType?: Sbmltype16;
  id?: Id16;
  metaId?: Metaid16;
  name?: Name16;
  sbo?: Sbo16;
  notes?: Notes16;
  cvterms?: Cvterms16;
  history?: ModelHistory | null;
  xml?: Xml16;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties16;
  math?: Math | null;
  derivedUnits?: Derivedunits7;
  listOfLocalParameters?: Listoflocalparameters;
}
/**
 * A local parameter of a kinetic law.
 */
export interface LocalParameter {
  pk: Pk17;
  sbmlType?: Sbmltype17;
  id?: Id17;
  metaId?: Metaid17;
  name?: Name17;
  sbo?: Sbo17;
  notes?: Notes17;
  cvterms?: Cvterms17;
  history?: ModelHistory | null;
  xml?: Xml17;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties17;
  value?: Value3;
  units?: Units4;
  unitsLatex?: Unitslatex4;
  derivedUnits?: Derivedunits8;
}
/**
 * The fbc extension of a reaction.
 *
 * `gene_products` are the ids referenced by the association, so that the
 * link graph does not parse the infix string.
 */
export interface ReactionFbc {
  lowerFluxBound?: Lowerfluxbound;
  upperFluxBound?: Upperfluxbound;
  geneProductAssociation?: Geneproductassociation;
  geneProducts?: Geneproducts;
}
/**
 * An event with trigger, priority, delay and assignments.
 */
export interface Event {
  pk: Pk18;
  sbmlType?: Sbmltype18;
  id?: Id18;
  metaId?: Metaid18;
  name?: Name18;
  sbo?: Sbo18;
  notes?: Notes18;
  cvterms?: Cvterms18;
  history?: ModelHistory | null;
  xml?: Xml18;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties18;
  useValuesFromTriggerTime?: Usevaluesfromtriggertime;
  trigger?: Trigger | null;
  priority?: Math | null;
  delay?: Math | null;
  listOfEventAssignments?: Listofeventassignments;
}
/**
 * The trigger of an event.
 */
export interface Trigger {
  math?: Math | null;
  initialValue?: Initialvalue;
  persistent?: Persistent;
}
/**
 * An assignment executed by an event.
 */
export interface EventAssignment {
  pk: Pk19;
  sbmlType?: Sbmltype19;
  id?: Id19;
  metaId?: Metaid19;
  name?: Name19;
  sbo?: Sbo19;
  notes?: Notes19;
  cvterms?: Cvterms19;
  history?: ModelHistory | null;
  xml?: Xml19;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties19;
  variable: Variable2;
  math?: Math | null;
}
/**
 * A comp submodel instantiating a model definition.
 */
export interface Submodel {
  pk: Pk20;
  sbmlType?: Sbmltype20;
  id?: Id20;
  metaId?: Metaid20;
  name?: Name20;
  sbo?: Sbo20;
  notes?: Notes20;
  cvterms?: Cvterms20;
  history?: ModelHistory | null;
  xml?: Xml20;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties20;
  modelRef: Modelref;
  timeConversionFactor?: Timeconversionfactor;
  extentConversionFactor?: Extentconversionfactor;
  listOfDeletions?: Listofdeletions;
}
/**
 * A comp port referencing an element of the model.
 */
export interface Port {
  pk: Pk21;
  sbmlType?: Sbmltype21;
  id?: Id21;
  metaId?: Metaid21;
  name?: Name21;
  sbo?: Sbo21;
  notes?: Notes21;
  cvterms?: Cvterms21;
  history?: ModelHistory | null;
  xml?: Xml21;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties21;
  portRef?: Portref1;
  idRef?: Idref1;
  unitRef?: Unitref1;
  metaIdRef?: Metaidref1;
}
/**
 * An fbc gene product.
 */
export interface GeneProduct {
  pk: Pk22;
  sbmlType?: Sbmltype22;
  id?: Id22;
  metaId?: Metaid22;
  name?: Name22;
  sbo?: Sbo22;
  notes?: Notes22;
  cvterms?: Cvterms22;
  history?: ModelHistory | null;
  xml?: Xml22;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties22;
  label?: Label;
  associatedSpecies?: Associatedspecies;
}
/**
 * An fbc objective.
 */
export interface Objective {
  pk: Pk23;
  sbmlType?: Sbmltype23;
  id?: Id23;
  metaId?: Metaid23;
  name?: Name23;
  sbo?: Sbo23;
  notes?: Notes23;
  cvterms?: Cvterms23;
  history?: ModelHistory | null;
  xml?: Xml23;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties23;
  type?: Type1;
  listOfFluxObjectives?: Listoffluxobjectives;
}
/**
 * A weighted reaction of an objective.
 */
export interface FluxObjective {
  reaction: Reaction1;
  coefficient?: Coefficient;
}
/**
 * A comp reference to a model in another document.
 */
export interface ExternalModelDefinition {
  pk: Pk24;
  sbmlType?: Sbmltype24;
  id?: Id24;
  metaId?: Metaid24;
  name?: Name24;
  sbo?: Sbo24;
  notes?: Notes24;
  cvterms?: Cvterms24;
  history?: ModelHistory | null;
  xml?: Xml24;
  comp?: CompSBase | null;
  uncertainties?: Uncertainties24;
  source: Source;
  modelRef?: Modelref1;
}
/**
 * All objects of a report and the references between them.
 */
export interface LinkGraph {
  nodes?: Nodes;
  edges?: Edges;
}
export interface Nodes {
  [k: string]: Node;
}
/**
 * A node of the link graph: one SBML object.
 *
 * Nodes are immutable values, so that they can be used in sets and as keys.
 */
export interface Node {
  pk: Pk25;
  sbmlType: Sbmltype25;
  id?: Id25;
  name?: Name25;
  model?: Model1;
}
/**
 * A directed reference from one object to another.
 *
 * Edges are immutable values, so that they can be used in sets and as keys.
 */
export interface Edge {
  source: Source1;
  target: Target;
  kind: EdgeKind;
}
/**
 * Timing information of a report.
 */
export interface Debug {
  jsonReportTime: Jsonreporttime;
}
