/* eslint-disable */
// Generated by 'npm run types' from src/schema/report.schema.json, do not edit.

/**
 * The kinds of references between objects.
 */
export type EdgeKind =
  | "compartment"
  | "reactant"
  | "product"
  | "modifier"
  | "trigger"
  | "priority"
  | "delay"
  | "variable"
  | "symbol"
  | "units"
  | "conversionFactor"
  | "fluxBound"
  | "geneProduct"
  | "associatedSpecies"
  | "fluxObjective"
  | "modelRef"
  | "port"
  | "replacedBy"
  | "replacedElement"
  | "math";

/**
 * The response of the api: the manifest and one report per SBML entry.
 */
export interface ReportResponse {
  uid: string;
  manifest: Manifest;
  reports: {
    [k: string]: ReportEntry;
  };
}
/**
 * The manifest of a COMBINE archive.
 */
export interface Manifest {
  entries?: ManifestEntry[];
}
/**
 * An entry of the manifest of a COMBINE archive.
 */
export interface ManifestEntry {
  location: string;
  format: string;
  master?: boolean;
}
/**
 * The report of one SBML entry of an archive.
 */
export interface ReportEntry {
  report: Report;
  debug: Debug;
}
/**
 * The report of one SBML document.
 */
export interface Report {
  document: SBMLDocument;
  models?: Model[];
  externalModelDefinitions?: ExternalModelDefinition[];
  linkGraph?: LinkGraph;
}
/**
 * The document: level, version and the packages it uses.
 *
 * `annotation_xml` takes the place of the `xml` of every other element, which
 * is not part of the report for the document and the model because it is the
 * whole file.
 */
export interface SBMLDocument {
  pk: string;
  sbmlType?: "SBMLDocument";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  level: number;
  version: number;
  packages?: Package[];
  annotationXml?: string | null;
}
/**
 * An annotation: a qualifier (BQB or BQM of pymetadata) with its resources.
 *
 * A term can carry terms of its own, which qualify it further: the evidence
 * for a relation or the modification of a protein (core §6).
 */
export interface CVTerm {
  qualifier: string;
  resources: string[];
  nested?: CVTerm[];
}
/**
 * The history of an element: creators and dates.
 */
export interface ModelHistory {
  creators?: Creator[];
  createdDate?: string | null;
  modifiedDates?: string[];
}
/**
 * A creator of the model history.
 */
export interface Creator {
  givenName?: string | null;
  familyName?: string | null;
  organization?: string | null;
  email?: string | null;
}
/**
 * The comp extension of an element.
 */
export interface CompSBase {
  replacedBy?: ReplacedBy | null;
  replacedElements?: ReplacedElement[];
}
/**
 * The element of a submodel which replaces this element.
 */
export interface ReplacedBy {
  pk: string;
  sbmlType?: "ReplacedBy";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  portRef?: string | null;
  idRef?: string | null;
  unitRef?: string | null;
  metaIdRef?: string | null;
  sbaseRef?: SBaseRef | null;
  submodelRef: string;
}
/**
 * A distrib uncertainty of an element.
 */
export interface Uncertainty {
  pk: string;
  sbmlType?: "Uncertainty";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  uncertParameters?: UncertParameter[];
}
/**
 * A parameter of a distrib uncertainty.
 */
export interface UncertParameter {
  var?: string | null;
  value?: number | null;
  units?: string | null;
  type?: string | null;
  definitionUrl?: string | null;
  math?: Math | null;
}
/**
 * The math of an element as latex and as L3 formula string.
 */
export interface Math {
  latex: string;
  formula: string;
}
/**
 * A link of a reference chain, which names an element of a submodel.
 *
 * The chain starts at a port, a deletion, a replaced element or a replaced
 * by, whose reference names a submodel; every further link names an element
 * of the model that submodel instantiates (comp §3.7.2).
 */
export interface SBaseRef {
  pk: string;
  sbmlType?: "SBaseRef";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  portRef?: string | null;
  idRef?: string | null;
  unitRef?: string | null;
  metaIdRef?: string | null;
  sbaseRef?: SBaseRef | null;
}
/**
 * An element of a submodel which this element replaces.
 */
export interface ReplacedElement {
  pk: string;
  sbmlType?: "ReplacedElement";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  portRef?: string | null;
  idRef?: string | null;
  unitRef?: string | null;
  metaIdRef?: string | null;
  sbaseRef?: SBaseRef | null;
  submodelRef: string;
  deletion?: string | null;
  conversionFactor?: string | null;
}
/**
 * An SBML package used by the document.
 */
export interface Package {
  prefix: string;
  version: number;
}
/**
 * A model or comp model definition with the lists of its elements.
 *
 * `annotation_xml` takes the place of the `xml` of every other element, which
 * is not part of the report for the document and the model because it is the
 * whole file.
 */
export interface Model {
  pk: string;
  sbmlType?: "Model";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  kind?: "model" | "modelDefinition";
  annotationXml?: string | null;
  substanceUnits?: string | null;
  substanceUnitsLatex?: string | null;
  timeUnits?: string | null;
  timeUnitsLatex?: string | null;
  volumeUnits?: string | null;
  volumeUnitsLatex?: string | null;
  areaUnits?: string | null;
  areaUnitsLatex?: string | null;
  lengthUnits?: string | null;
  lengthUnitsLatex?: string | null;
  extentUnits?: string | null;
  extentUnitsLatex?: string | null;
  conversionFactor?: ConversionFactor | null;
  listOfFunctionDefinitions?: FunctionDefinition[];
  listOfUnitDefinitions?: UnitDefinition[];
  listOfCompartments?: Compartment[];
  listOfSpecies?: Species[];
  listOfParameters?: Parameter[];
  listOfInitialAssignments?: InitialAssignment[];
  listOfRules?: (AssignmentRule | RateRule | AlgebraicRule)[];
  listOfConstraints?: Constraint[];
  listOfReactions?: Reaction[];
  listOfEvents?: Event[];
  listOfSubmodels?: Submodel[];
  listOfPorts?: Port[];
  listOfGeneProducts?: GeneProduct[];
  listOfObjectives?: Objective[];
}
/**
 * The conversion factor parameter of a model or species.
 */
export interface ConversionFactor {
  sid: string;
  value?: number | null;
  units?: string | null;
}
/**
 * A function definition with its lambda.
 */
export interface FunctionDefinition {
  pk: string;
  sbmlType?: "FunctionDefinition";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  math?: Math | null;
}
/**
 * A unit definition with its units and their rendered formula.
 */
export interface UnitDefinition {
  pk: string;
  sbmlType?: "UnitDefinition";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  unitsLatex?: string | null;
  listOfUnits?: Unit[];
}
/**
 * One factor of a unit definition: a base unit with exponent, scale and multiplier.
 *
 * A unit carries no identifier and nothing in SBML refers to it, so it is a
 * nested object of its definition and not an element of the report with a
 * primary key of its own.
 */
export interface Unit {
  kind?: string | null;
  exponent?: number | null;
  scale?: number | null;
  multiplier?: number | null;
}
/**
 * A compartment.
 */
export interface Compartment {
  pk: string;
  sbmlType?: "Compartment";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  spatialDimensions?: number | null;
  size?: number | null;
  constant?: boolean | null;
  units?: string | null;
  unitsLatex?: string | null;
  derivedUnits?: string | null;
}
/**
 * A species.
 */
export interface Species {
  pk: string;
  sbmlType?: "Species";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  compartment: string;
  initialAmount?: number | null;
  initialConcentration?: number | null;
  substanceUnits?: string | null;
  hasOnlySubstanceUnits?: boolean | null;
  boundaryCondition?: boolean | null;
  constant?: boolean | null;
  unitsLatex?: string | null;
  derivedUnits?: string | null;
  conversionFactor?: ConversionFactor | null;
  fbc?: SpeciesFbc | null;
}
/**
 * The fbc extension of a species.
 */
export interface SpeciesFbc {
  chemicalFormula?: string | null;
  charge?: number | null;
}
/**
 * A global parameter.
 */
export interface Parameter {
  pk: string;
  sbmlType?: "Parameter";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  value?: number | null;
  constant?: boolean | null;
  units?: string | null;
  unitsLatex?: string | null;
  derivedUnits?: string | null;
}
/**
 * An initial assignment of a symbol.
 */
export interface InitialAssignment {
  pk: string;
  sbmlType?: "InitialAssignment";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  symbol: string;
  math?: Math | null;
  derivedUnits?: string | null;
}
/**
 * An assignment rule of a variable.
 */
export interface AssignmentRule {
  pk: string;
  sbmlType?: "AssignmentRule";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  variable: string;
  math?: Math | null;
  derivedUnits?: string | null;
}
/**
 * A rate rule of a variable.
 */
export interface RateRule {
  pk: string;
  sbmlType?: "RateRule";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  variable: string;
  math?: Math | null;
  derivedUnits?: string | null;
}
/**
 * An algebraic rule.
 */
export interface AlgebraicRule {
  pk: string;
  sbmlType?: "AlgebraicRule";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  math?: Math | null;
  derivedUnits?: string | null;
}
/**
 * A constraint with its message.
 */
export interface Constraint {
  pk: string;
  sbmlType?: "Constraint";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  math?: Math | null;
  message?: string | null;
}
/**
 * A reaction with its participants and kinetic law.
 *
 * `equation` is the readable equation, its half equations joined by a plain
 * unicode arrow: "⇆" (U+21C6) for a reversible reaction, "➞" (U+279E)
 * otherwise.
 */
export interface Reaction {
  pk: string;
  sbmlType?: "Reaction";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  reversible?: boolean | null;
  fast?: boolean | null;
  compartment?: string | null;
  listOfReactants?: SpeciesReference[];
  listOfProducts?: SpeciesReference[];
  listOfModifiers?: ModifierSpeciesReference[];
  kineticLaw?: KineticLaw | null;
  equation: string;
  fbc?: ReactionFbc | null;
}
/**
 * A reactant or product of a reaction.
 */
export interface SpeciesReference {
  pk: string;
  sbmlType?: "SpeciesReference";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  species: string;
  stoichiometry?: number | null;
  constant?: boolean | null;
}
/**
 * A modifier of a reaction.
 */
export interface ModifierSpeciesReference {
  pk: string;
  sbmlType?: "ModifierSpeciesReference";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  species: string;
}
/**
 * The kinetic law of a reaction.
 */
export interface KineticLaw {
  pk: string;
  sbmlType?: "KineticLaw";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  math?: Math | null;
  derivedUnits?: string | null;
  listOfLocalParameters?: LocalParameter[];
}
/**
 * A local parameter of a kinetic law.
 */
export interface LocalParameter {
  pk: string;
  sbmlType?: "LocalParameter";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  value?: number | null;
  units?: string | null;
  unitsLatex?: string | null;
  derivedUnits?: string | null;
}
/**
 * The fbc extension of a reaction.
 *
 * `gene_products` are the ids referenced by the association, so that the
 * link graph does not parse the infix string.
 */
export interface ReactionFbc {
  lowerFluxBound?: string | null;
  upperFluxBound?: string | null;
  geneProductAssociation?: string | null;
  geneProducts?: string[];
}
/**
 * An event with trigger, priority, delay and assignments.
 */
export interface Event {
  pk: string;
  sbmlType?: "Event";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  useValuesFromTriggerTime?: boolean | null;
  trigger?: Trigger | null;
  priority?: Priority | null;
  delay?: Delay | null;
  listOfEventAssignments?: EventAssignment[];
}
/**
 * The trigger of an event: the condition which fires it.
 */
export interface Trigger {
  pk: string;
  sbmlType?: "Trigger";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  math?: Math | null;
  initialValue?: boolean | null;
  persistent?: boolean | null;
}
/**
 * The priority of an event: the order of the events of one moment.
 */
export interface Priority {
  pk: string;
  sbmlType?: "Priority";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  math?: Math | null;
}
/**
 * The delay of an event: the time between the trigger and the execution.
 */
export interface Delay {
  pk: string;
  sbmlType?: "Delay";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  math?: Math | null;
}
/**
 * An assignment executed by an event.
 */
export interface EventAssignment {
  pk: string;
  sbmlType?: "EventAssignment";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  variable: string;
  math?: Math | null;
}
/**
 * A comp submodel instantiating a model definition.
 */
export interface Submodel {
  pk: string;
  sbmlType?: "Submodel";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  modelRef: string;
  timeConversionFactor?: string | null;
  extentConversionFactor?: string | null;
  listOfDeletions?: Deletion[];
}
/**
 * An element of a submodel which is removed before it is instantiated.
 */
export interface Deletion {
  pk: string;
  sbmlType?: "Deletion";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  portRef?: string | null;
  idRef?: string | null;
  unitRef?: string | null;
  metaIdRef?: string | null;
  sbaseRef?: SBaseRef | null;
}
/**
 * A comp port referencing an element of the model.
 */
export interface Port {
  pk: string;
  sbmlType?: "Port";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  portRef?: string | null;
  idRef?: string | null;
  unitRef?: string | null;
  metaIdRef?: string | null;
  sbaseRef?: SBaseRef | null;
}
/**
 * An fbc gene product.
 */
export interface GeneProduct {
  pk: string;
  sbmlType?: "GeneProduct";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  label?: string | null;
  associatedSpecies?: string | null;
}
/**
 * An fbc objective.
 */
export interface Objective {
  pk: string;
  sbmlType?: "Objective";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  type?: string | null;
  listOfFluxObjectives?: FluxObjective[];
}
/**
 * A weighted reaction of an objective.
 */
export interface FluxObjective {
  reaction: string;
  coefficient?: number | null;
}
/**
 * A comp reference to a model in another document.
 */
export interface ExternalModelDefinition {
  pk: string;
  sbmlType?: "ExternalModelDefinition";
  id?: string | null;
  metaId?: string | null;
  name?: string | null;
  sbo?: string | null;
  notes?: string | null;
  cvterms?: CVTerm[];
  history?: ModelHistory | null;
  xml?: string | null;
  comp?: CompSBase | null;
  uncertainties?: Uncertainty[];
  source: string;
  modelRef?: string | null;
  md5?: string | null;
}
/**
 * All objects of a report and the references between them.
 */
export interface LinkGraph {
  nodes?: {
    [k: string]: Node;
  };
  edges?: Edge[];
}
/**
 * A node of the link graph: one SBML object.
 *
 * Nodes are immutable values, so that they can be used in sets and as keys.
 */
export interface Node {
  pk: string;
  sbmlType: string;
  id?: string | null;
  name?: string | null;
  model?: string | null;
}
/**
 * A directed reference from one object to another.
 *
 * Edges are immutable values, so that they can be used in sets and as keys.
 */
export interface Edge {
  source: string;
  target: string;
  kind: EdgeKind;
}
/**
 * Timing information of a report.
 */
export interface Debug {
  jsonReportTime: string;
}
