/* eslint-disable */
// Generated by 'npm run types' from src/schema/validation.schema.json, do not edit.

/**
 * The response of a validation endpoint: one validation per SBML entry.
 *
 * The entries are keyed and ordered like the reports of the report response
 * of the same source. `skipped` says why the validation stopped early, which
 * is also the reason of every entry it did not reach; an entry it did not
 * even read is missing from `entries` (all of them for `busy`).
 */
export interface ValidationResponse {
  entries: {
    [k: string]: EntryValidation;
  };
  skipped: ("expandedSize" | "timeout" | "memory" | "crashed" | "busy") | null;
}
/**
 * The validation of libsbml of one SBML entry of a report.
 *
 * `skipped` says why the consistency of the document was not checked, in
 * which case `issues` holds the issues of reading it alone, or none:
 * `expandedSize`, the document expands by its comp submodels to more
 * elements than are checked in a bounded time, with the read issues;
 * `timeout`, the check did not end in time; `memory`, the check needed more
 * memory than it may use; `crashed`, the process of the check ended
 * abnormally for another reason; `busy`, the server had no room for the
 * check.
 */
export interface EntryValidation {
  issues: ValidationIssue[];
  skipped: ("expandedSize" | "timeout" | "memory" | "crashed" | "busy") | null;
}
/**
 * An error, a warning or a note of the validation of libsbml.
 *
 * libsbml reports the line and the column of an issue, not its element: the
 * pk is the element which starts closest before that position (the document
 * when none does). The texts are those of libsbml.
 */
export interface ValidationIssue {
  rule: number;
  severity: "error" | "warning" | "info";
  category: string;
  shortMessage: string;
  message: string;
  line: number;
  column: number;
  pk: string;
}
